### ISSUE TITLE
Return to List

### ISSUE THREAD

**Issue by nasteffe** [giovannicoppola/alfred-readwise#2]
Thank you for putting together this workflow! I was hoping something like this existed for Alfred. 

What stands out to me, however, is how much text I want to read for each highlight, far more than exists on each line, simply to bring it back to mind. I could hit the return key and then read it in large type, but then escaping from the large type would not bring me back to the highlights list. I naively tried quicklook (despite each highlight not being its own file), but no luck. Any suggestions?

**Comment by giovannicoppola** [comment]
great idea!! I added this option (Shift-Enter). Let me know if it works!
https://github.com/giovannicoppola/alfred-readwise/releases/download/v0.2.1/alfred-readwise_0.2.1.alfredworkflow

**Comment by nasteffe** [comment]
Wow, thank you for being so responsive! I'm afraid that the Alfred is still closing for me, even though the Window Behavior is set to Alfred not closing after actioning.

**Comment by giovannicoppola** [comment]
? after Shift-enter and Esc to close the large text? It seems to work fine

**Comment by nasteffe** [comment]
Then I must have something that's getting in the way. I will keep tinkering until I find it. Thank you for adding that in!

**Comment by giovannicoppola** [comment]
you downloaded the workflow again and updated it, right?

**Comment by nasteffe** [comment]
Yes, I deleted the old one and reinstalled the new one.

**Comment by nasteffe** [comment]
Ok, I tracked down my problem. I had the "auto hide alfred when showing large type" setting checked. If I'm using large type directly within alfred, then the alfred reappears. But apparently leaving it checked and then using large type in a workflow led to the alfred search window not reappearing. 

I unchecked the setting and your workflow worked wonderfully. Thanks!

**Comment by nasteffe** [comment]
Recognizing I closed this already, I had an additional, though related, question. Would it be possible to use the Quicklook feature with the Readwise highlights? I tried to initiate it, but nothing came up. If that feature could be added to this workflow, then it would make it even easier to see the complete highlights while scrolling through them.

**Comment by giovannicoppola** [comment]
thanks @nasteffe we would need to create an image for each highlight. I tried it [here](https://github.com/giovannicoppola/alfred-readwise/blob/main/releases/alfred-readwise_0.3.alfredworkflow). two possible problems with this:
1) it takes a while to generate all the files, if there are many new highlights (I could make it optional)
2) not sure it works for very long highlights (could make the font size customizable). 
let me know what you think!

**Comment by giovannicoppola** [comment]
@nasteffe curious if you had a chance to review the new version?
